/*
 * CloverDiscordLink • автор slyph
 * Paper 1.20+ / Java 17 / JDA-5 «fat-jar» через Shadow
 */

plugins {
    id 'java'
    id 'com.github.johnrengelman.shadow' version '8.1.1'
    id 'xyz.jpenilla.run-paper'          version '2.3.1'
}

group   = 'com.slyph'
version = '1.4.3'

repositories {
    mavenCentral()
    maven { url = 'https://repo.papermc.io/repository/maven-public/' }
    maven { url = 'https://m2.dv8tion.net/releases' }           // JDA
}

dependencies {
    /* API Paper 1.20.1 — компилируемся под новую, но в plugin.yml
       оставляем api-version: 1.16 чтобы плагин спокойно шёл и на 1.16-1.20 */
    compileOnly 'io.papermc.paper:paper-api:1.20.1-R0.1-SNAPSHOT'
    runtimeOnly("com.mysql:mysql-connector-j:8.3.0")
    /* Discord SDK (будет за-shade-ен внутрь JAR-файла) */
    implementation('net.dv8tion:JDA:5.0.0-beta.23') {
        exclude module: 'opus-java'   // нативка для войса не нужна
    }
}

/* ---------- Java 17 ---------- */
java {
    toolchain.languageVersion = JavaLanguageVersion.of(17)
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release.set(17)
}

/* ---------- Shadow (fat-jar) ---------- */
shadowJar {
    archiveClassifier.set('')                        // итоговый JAR без «-all»
}

/* ---------- run-paper (dev-сервер) ---------- */
tasks.runServer {
    minecraftVersion '1.20.1'    // сервер для тестов
    dependsOn shadowJar          // запускаем именно «жирный» JAR
}

/* ---------- plugin.yml автозамена версии ---------- */
processResources {
    def props = [version: project.version]
    inputs.properties props
    filteringCharset 'UTF-8'
    filesMatching('plugin.yml') { expand props }
}
