name: CloverDiscordLink
main: dev.fread.discordbridge.DiscordChatBridge
version: ${version}
api-version: 1.16
author: slyph
description: Discord integration and account linking for Minecraft
commands:
  dchat:
    description: Reload CloverDiscordLink configuration
    usage: /<command> reload
    permission: dchat.reload
permissions:
  dchat.reload:
    description: Allows you to reload the plugin config
    default: op
